
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://34.89.114.242:3306/TTDS_group7'
    username: 'root'
    password: '!ttds2021'

  redis:
    host: 'gc.caohongchuan.top'
    port: 6379
    jedis:
      pool:
        max-active: 8
    database: 1
    password: '!ttds2021'

newsrecommend:
  activeDays: -10
  KEY_WORDS_NUM: 10
  NEWS_RECOMMEND_NUM: 10
  DEC_COEE: 0.1
  CFRecNum: 10
  CFValidDays: -5
  beforeDays: -5
  TOTAL_REC_NUM: 20
  HotNewsLimit: 30